name: Scheduled Posts Publisher

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run against'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging
          - development
      debug:
        description: 'Enable debug mode'
        required: false
        default: false
        type: boolean

jobs:
  publish-scheduled-posts:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Publishing API
        run: |
          curl -X GET https://pingpost.vercel.app/api/cron/publishScheduled \ 
          -H "Authorization: Bearer TestCronSec"
        
      - name: Log completion
        run: echo "Scheduled posts publication triggered"

        

